export { VaccinesSection } from './Vaccines'
export { ConsultationsSection } from './Consultations'
export { MedicationsSection } from './Medications'
export { ClinicalHistorySection } from './ClinicalHistory'
export { EmergencySection } from './Emergency'
